### PR TITLE
Don't autofocus the compose form

### PR DESCRIPTION
**Pull request by raboof**
This is a cherry-pick of https://github.com/mastodon/mastodon/pull/16517 to give it some wider testing and collect feedback.

When opening a page such as /web/timelines/home in a desktop browser, the
cursor was automatically placed in the textarea of the compose form.

When using the keyboard for navigation (using a browser plugin like vimium or
vim vixen, or just to hit 'space' to scroll down a page), you have remember to
leave the field before using that.

Since you only visit the page to write a new post some of the time, this PR
attempts to have nothing focused initially (and require the user to click or
e.g. use 'tab' to focus the textarea).

Tested:
* /web/timeslines/home no longer autofocuses the compose box
* pressing the 'n' hotkey still focuses the compose box
* clicking 'reply' for a post still focuses the compose box
* replying to a CW'ed post still focuses the compose box
* introducing the CW field still focuses the CW field
* introducing the CW field for a reply still focuses the CW field
* removing the CW field still focuses the compose box
* /web/statuses/new still autofocuses the compose box

### CODE REVIEW

**Comment by SomniusTiger** [comment]
I like this idea! One thing though: would you mind rebasing this topic branch off the main `merveilles` branch in the `merveilles-town` repo, please? That will give me a better idea of what files get touched to merge this change!

**Comment by raboof** [comment]
Rebased!

**Comment by SomniusTiger** [comment]
Thank you! Will take a look soon, appreciate your patience and efforts here.

**Comment by raboof** [comment]
This made it into `v1.0.6+3.5.2` of hometown (https://github.com/hometown-fork/hometown/pull/1156) so this PR is no longer needed, we will just get it when we update to a newer version of hometown

**Pull request closed without merging**
