### PR TITLE
CSS Style Tweaks

### PR DESCRIPTION
**Pull request by SomniusTiger**
This consists of some CSS tweaks I've been meaning to get around to for a while. This adds:

- Fixes linter errors from `sass-lint`
- A custom bookmark icon
- Adds better default "no avatar set yet" image
- Many styles in the settings page have been adjusted for consistency (buttons, tables, inputs, etc)
- Admin style settings
- Public page & public header styles

### CODE REVIEW

**Comment by SomniusTiger** [comment]
Some screenshots that show the updates (don't mind the default mastodon mascot, that's just my local dev environment):

Screenshot 2020-06-21 01 34 44

Screenshot 2020-06-21 01 35 28

Screenshot 2020-06-21 01 38 03

Screenshot 2020-06-21 01 38 16

**Comment by SomniusTiger** [comment]
More tweaks here:

Screenshot 2020-06-21 02 12 21

Screenshot 2020-06-21 02 12 38

Screenshot 2020-06-21 02 15 49

**Comment by cblgh** [comment]
ohhh! I LOVE THE NEW ANNOUNCEMENTS STYLING!

also hooray for the custom bookmark icon :) thanks again somnius :3

**Comment by SomniusTiger** [comment]
Build passed! Merging & deploying shortly~

**Pull request merged**
